version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  angular:
    build: client
    ports:
      - "4200:4200"
    volumes:
      - './client:/client'
      - /client/node_modules
  express:
    build: server
    ports:
      - "4000:4000"
    volumes:
      - './server:/server'
      - /server/node_modules
volumes:
  mysql: ~